version: "3"
services:
  frigate:
    container_name: frigate
    # add groups from host for render, plugdev, video
    group_add:
      - "109" # render
      - "110" # render
      - "44" # video
      - "46" # plugdev
    shm_size: "256mb"
    image: ghcr.io/blakeblackshear/frigate:stable
    environment:
      YOLO_MODELS: yolov7-320
    devices:
      - /dev/bus/usb/002/003:/dev/bus/usb/002/003
    volumes:
      - .:/workspace/frigate:cached
      # - ./web/dist:/opt/frigate/web:cached
      # - ./web:/opt/frigate/web:cached
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./debug:/media/frigate
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    networks:
      - mqtt

networks:
  mqtt:
    external: true
